<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        $clientUserIds = DB::table('users')->where('role_id', 2)->pluck('id')->toArray();
        $statuses      = ['open', 'in_progress', 'closed'];
        $budgetTypes   = ['fixed', 'hourly'];

        $projects = [
            [
                'title'       => 'تطوير موقع شركة عقارية',
                'description' => 'نحتاج موقعاً احترافياً لشركة عقارية يتضمن قائمة العقارات مع إمكانية البحث والتصفية وصفحة تواصل معنا وصفحة عن الشركة. يجب أن يكون الموقع متجاوباً مع جميع الأجهزة.',
                'budget_type' => 'fixed',
                'fixed_price' => 1500,
                'hourly_price'=> null,
                'date'        => now()->addDays(30)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'تصميم هوية بصرية لمطعم',
                'description' => 'تصميم هوية بصرية متكاملة لمطعم شرقي جديد تشمل الشعار والألوان والخطوط والقوائم والمطبوعات.',
                'budget_type' => 'fixed',
                'fixed_price' => 800,
                'hourly_price'=> null,
                'date'        => now()->addDays(20)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'تطوير تطبيق موبايل لتوصيل الطلبات',
                'description' => 'تطوير تطبيق توصيل طلبات للمطاعم يعمل على Android وiOS مع لوحة تحكم للمطاعم وميزة تتبع السائق في الوقت الفعلي.',
                'budget_type' => 'fixed',
                'fixed_price' => 4500,
                'hourly_price'=> null,
                'date'        => now()->addDays(90)->toDateString(),
                'status'      => 'in_progress',
            ],
            [
                'title'       => 'إدارة حسابات التواصل الاجتماعي',
                'description' => 'إدارة حسابات الشركة على انستغرام وفيسبوك وتويتر مع إنشاء محتوى يومي وحملات إعلانية شهرية.',
                'budget_type' => 'hourly',
                'fixed_price' => null,
                'hourly_price'=> 25,
                'date'        => now()->addDays(60)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'كتابة محتوى تقني لمدونة',
                'description' => 'كتابة 20 مقالاً تقنياً شهرياً في مجال التكنولوجيا والبرمجة لمدونة متخصصة، يجب أن يكون المحتوى محسناً لمحركات البحث.',
                'budget_type' => 'fixed',
                'fixed_price' => 600,
                'hourly_price'=> null,
                'date'        => now()->addDays(25)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'بناء متجر إلكتروني على Shopify',
                'description' => 'بناء متجر إلكتروني احترافي على Shopify لبيع ملابس الأطفال مع تخصيص القالب وإضافة المنتجات وإعداد بوابات الدفع.',
                'budget_type' => 'fixed',
                'fixed_price' => 1200,
                'hourly_price'=> null,
                'date'        => now()->addDays(45)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'تصميم تطبيق موبايل (UI/UX)',
                'description' => 'تصميم واجهات تطبيق موبايل لخدمة حجز المواعيد الطبية مع تجربة مستخدم سلسة وسهلة الاستخدام.',
                'budget_type' => 'fixed',
                'fixed_price' => 900,
                'hourly_price'=> null,
                'date'        => now()->addDays(35)->toDateString(),
                'status'      => 'in_progress',
            ],
            [
                'title'       => 'تطوير API للربط مع تطبيق موبايل',
                'description' => 'تطوير REST API باستخدام Laravel للربط مع تطبيق موبايل قائم يتضمن نظام مصادقة والإشعارات الفورية وإدارة البيانات.',
                'budget_type' => 'hourly',
                'fixed_price' => null,
                'hourly_price'=> 40,
                'date'        => now()->addDays(50)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'تحسين سرعة موقع WordPress',
                'description' => 'تحسين سرعة وأداء موقع WordPress موجود مع تحسين SEO التقني وإصلاح الأخطاء وتقليل وقت التحميل إلى أقل من 2 ثانية.',
                'budget_type' => 'fixed',
                'fixed_price' => 400,
                'hourly_price'=> null,
                'date'        => now()->addDays(15)->toDateString(),
                'status'      => 'closed',
            ],
            [
                'title'       => 'تحليل بيانات مبيعات شركة',
                'description' => 'تحليل بيانات مبيعات الشركة للسنوات الثلاث الماضية وإعداد تقارير وداشبورد تفاعلي يوضح الاتجاهات والتوقعات المستقبلية.',
                'budget_type' => 'fixed',
                'fixed_price' => 700,
                'hourly_price'=> null,
                'date'        => now()->addDays(40)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'برمجة chatbot خدمة عملاء',
                'description' => 'تطوير chatbot ذكي للرد على استفسارات العملاء على واتساب وفيسبوك ماسنجر مع ربطه بنظام CRM الحالي.',
                'budget_type' => 'fixed',
                'fixed_price' => 2000,
                'hourly_price'=> null,
                'date'        => now()->addDays(55)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'تصوير منتجات لمتجر إلكتروني',
                'description' => 'تصوير 150 منتج بخلفية بيضاء وبخلفيات مشهدية مع معالجة الصور وتسليمها بجودة عالية للاستخدام في المتجر الإلكتروني.',
                'budget_type' => 'fixed',
                'fixed_price' => 550,
                'hourly_price'=> null,
                'date'        => now()->addDays(22)->toDateString(),
                'status'      => 'in_progress',
            ],
            [
                'title'       => 'ترجمة موقع إلكتروني من الإنجليزية إلى العربية',
                'description' => 'ترجمة موقع شركة تقنية من الإنجليزية إلى العربية مع مراعاة التعريب وتوجيه الصفحات RTL وضبط التخطيط.',
                'budget_type' => 'fixed',
                'fixed_price' => 350,
                'hourly_price'=> null,
                'date'        => now()->addDays(18)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'إعداد خادم Linux وضبط DevOps',
                'description' => 'إعداد خادم Ubuntu وضبط Docker Compose وNginx وSSL مع إعداد CI/CD pipeline على GitHub Actions.',
                'budget_type' => 'hourly',
                'fixed_price' => null,
                'hourly_price'=> 50,
                'date'        => now()->addDays(28)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'تطوير نظام إدارة مدرسة',
                'description' => 'نظام متكامل لإدارة مدرسة خاصة يشمل إدارة الطلاب والمعلمين والحضور والدرجات وإرسال إشعارات لأولياء الأمور.',
                'budget_type' => 'fixed',
                'fixed_price' => 5000,
                'hourly_price'=> null,
                'date'        => now()->addDays(120)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'تصميم موشن غرافيك لإعلان',
                'description' => 'تصميم فيديو موشن غرافيك مدته 60 ثانية للإعلان عن منتج جديد مع صوت وموسيقى خلفية مناسبة.',
                'budget_type' => 'fixed',
                'fixed_price' => 650,
                'hourly_price'=> null,
                'date'        => now()->addDays(14)->toDateString(),
                'status'      => 'closed',
            ],
            [
                'title'       => 'تطوير نظام نقاط بيع POS',
                'description' => 'نظام نقاط بيع متكامل للمحلات التجارية يدعم الباركود وإدارة المخزون والتقارير مع واجهة سريعة وسهلة الاستخدام.',
                'budget_type' => 'fixed',
                'fixed_price' => 3500,
                'hourly_price'=> null,
                'date'        => now()->addDays(75)->toDateString(),
                'status'      => 'in_progress',
            ],
            [
                'title'       => 'إنشاء قناة يوتيوب وتحريرها',
                'description' => 'إعداد قناة يوتيوب احترافية لشركة تعليمية وتحرير 10 فيديوهات شهرياً مع إضافة الغرافيكس والترجمة.',
                'budget_type' => 'hourly',
                'fixed_price' => null,
                'hourly_price'=> 30,
                'date'        => now()->addDays(45)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'بناء منصة تعليمية إلكترونية',
                'description' => 'منصة تعليمية متكاملة تدعم إنشاء الكورسات والدروس المباشرة والاختبارات وإدارة الطلاب مع نظام دفع إلكتروني.',
                'budget_type' => 'fixed',
                'fixed_price' => 8000,
                'hourly_price'=> null,
                'date'        => now()->addDays(150)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'تدقيق وتحسين كود Laravel',
                'description' => 'مراجعة كود تطبيق Laravel موجود وإصلاح الثغرات الأمنية وتحسين الأداء وإعادة هيكلة الكود وفق أفضل الممارسات.',
                'budget_type' => 'hourly',
                'fixed_price' => null,
                'hourly_price'=> 45,
                'date'        => now()->addDays(20)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'تصميم حزمة ستيشنري للشركة',
                'description' => 'تصميم حزمة ستيشنري متكاملة تشمل كارت الشخصية والظرف والورق الرسمي وملف الشركة والأقلام المطبوعة.',
                'budget_type' => 'fixed',
                'fixed_price' => 450,
                'hourly_price'=> null,
                'date'        => now()->addDays(12)->toDateString(),
                'status'      => 'closed',
            ],
            [
                'title'       => 'تطوير dashboard إحصائي',
                'description' => 'تطوير لوحة تحكم إحصائية تفاعلية باستخدام Vue.js و Chart.js تعرض بيانات المبيعات والزوار والأداء بشكل مرئي.',
                'budget_type' => 'fixed',
                'fixed_price' => 1100,
                'hourly_price'=> null,
                'date'        => now()->addDays(33)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'كتابة خطة عمل لمشروع ناشئ',
                'description' => 'كتابة خطة عمل احترافية لمشروع ناشئ في مجال التكنولوجيا تشمل تحليل السوق والمنافسين والخطة المالية للسنوات الثلاث الأولى.',
                'budget_type' => 'fixed',
                'fixed_price' => 500,
                'hourly_price'=> null,
                'date'        => now()->addDays(21)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'تطوير إضافة WordPress مخصصة',
                'description' => 'تطوير إضافة WordPress مخصصة لإدارة حجوزات الفنادق مع تقويم الحجز ونظام الدفع وإدارة الغرف.',
                'budget_type' => 'hourly',
                'fixed_price' => null,
                'hourly_price'=> 35,
                'date'        => now()->addDays(42)->toDateString(),
                'status'      => 'in_progress',
            ],
            [
                'title'       => 'إعداد حملة إعلانية Google Ads',
                'description' => 'إعداد وإدارة حملة إعلانية على Google Ads لمتجر إلكتروني مع استهداف الكلمات المفتاحية المناسبة وتتبع التحويلات.',
                'budget_type' => 'fixed',
                'fixed_price' => 380,
                'hourly_price'=> null,
                'date'        => now()->addDays(10)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'استشارة أمن معلومات وتقرير',
                'description' => 'إجراء اختبار اختراق شامل لتطبيق ويب وإعداد تقرير مفصل عن الثغرات المكتشفة مع توصيات للحل.',
                'budget_type' => 'fixed',
                'fixed_price' => 1800,
                'hourly_price'=> null,
                'date'        => now()->addDays(38)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'تصميم وتطوير نشرة بريدية',
                'description' => 'تصميم قالب نشرة بريدية HTML احترافي وبرمجته ليكون متوافقاً مع جميع عملاء البريد الإلكتروني.',
                'budget_type' => 'fixed',
                'fixed_price' => 280,
                'hourly_price'=> null,
                'date'        => now()->addDays(8)->toDateString(),
                'status'      => 'closed',
            ],
            [
                'title'       => 'تطوير نظام CRM للشركة',
                'description' => 'تطوير نظام CRM مخصص لإدارة العملاء والصفقات والمتابعات مع تقارير تفصيلية ونظام تنبيهات.',
                'budget_type' => 'fixed',
                'fixed_price' => 6500,
                'hourly_price'=> null,
                'date'        => now()->addDays(100)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'تحسين تجربة المستخدم لتطبيق قائم',
                'description' => 'مراجعة وتحسين تجربة المستخدم لتطبيق موبايل قائم بناءً على تحليل سلوك المستخدمين وإجراء اختبارات UX.',
                'budget_type' => 'hourly',
                'fixed_price' => null,
                'hourly_price'=> 38,
                'date'        => now()->addDays(30)->toDateString(),
                'status'      => 'in_progress',
            ],
            [
                'title'       => 'نظام إدارة مخزن ومستودع',
                'description' => 'نظام متكامل لإدارة المستودعات يشمل استقبال البضاعة وصرفها وإدارة الكميات والتنبيه عند نقص المخزون مع باركود.',
                'budget_type' => 'fixed',
                'fixed_price' => 2800,
                'hourly_price'=> null,
                'date'        => now()->addDays(65)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'إنشاء محتوى بودكاست',
                'description' => 'تحرير وإنتاج 8 حلقات بودكاست شهرياً مع تصميم الغلاف والجدول الزمني ونشرها على المنصات المختلفة.',
                'budget_type' => 'hourly',
                'fixed_price' => null,
                'hourly_price'=> 22,
                'date'        => now()->addDays(55)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'ربط نظام ERP بموقع الويب',
                'description' => 'ربط نظام ERP الداخلي بالموقع الإلكتروني لمزامنة بيانات المنتجات والمخزون والطلبات تلقائياً.',
                'budget_type' => 'hourly',
                'fixed_price' => null,
                'hourly_price'=> 55,
                'date'        => now()->addDays(48)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'كتابة نصوص إعلانية تسويقية',
                'description' => 'كتابة نصوص إعلانية لحملة تسويقية متكاملة تشمل الإعلانات المصورة والفيديو والبريد الإلكتروني ووسائل التواصل.',
                'budget_type' => 'fixed',
                'fixed_price' => 420,
                'hourly_price'=> null,
                'date'        => now()->addDays(16)->toDateString(),
                'status'      => 'closed',
            ],
            [
                'title'       => 'إعداد خطة تسويق رقمي سنوية',
                'description' => 'إعداد خطة تسويق رقمي سنوية شاملة لشركة ناشئة تتضمن تحديد الجمهور المستهدف والقنوات والميزانية والمؤشرات.',
                'budget_type' => 'fixed',
                'fixed_price' => 750,
                'hourly_price'=> null,
                'date'        => now()->addDays(27)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'تطوير نظام حجز مواعيد للعيادة',
                'description' => 'نظام حجز مواعيد إلكتروني للعيادات الطبية يدعم الحجز عبر الموقع والواتساب مع إرسال تذكيرات وإدارة الطبيب.',
                'budget_type' => 'fixed',
                'fixed_price' => 2200,
                'hourly_price'=> null,
                'date'        => now()->addDays(58)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'تصميم نماذج طباعية للشركة',
                'description' => 'تصميم مجموعة من النماذج الطباعية تشمل الفواتير والعقود وأوراق العمل وفق الهوية البصرية للشركة.',
                'budget_type' => 'fixed',
                'fixed_price' => 320,
                'hourly_price'=> null,
                'date'        => now()->addDays(10)->toDateString(),
                'status'      => 'in_progress',
            ],
            [
                'title'       => 'استشارة في بنية قاعدة البيانات',
                'description' => 'مراجعة وتحسين بنية قاعدة البيانات لتطبيق كبير مع تحسين الاستعلامات وإضافة الفهارس المناسبة لزيادة الأداء.',
                'budget_type' => 'hourly',
                'fixed_price' => null,
                'hourly_price'=> 60,
                'date'        => now()->addDays(14)->toDateString(),
                'status'      => 'closed',
            ],
            [
                'title'       => 'تطوير نظام تقييم ومراجعات',
                'description' => 'تطوير نظام تقييم ومراجعات متكامل لمنصة خدمات يشمل التقييم بالنجوم والتعليقات والرد عليها وإدارة الإساءة.',
                'budget_type' => 'fixed',
                'fixed_price' => 950,
                'hourly_price'=> null,
                'date'        => now()->addDays(36)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'مونتاج وتحرير فيديوهات تعليمية',
                'description' => 'تحرير ومونتاج 15 فيديو تعليمي مع إضافة المقدمات والخواتم والرسوم التوضيحية والترجمة العربية.',
                'budget_type' => 'fixed',
                'fixed_price' => 1300,
                'hourly_price'=> null,
                'date'        => now()->addDays(50)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'إنشاء نظام نشرة بريدية مؤتمتة',
                'description' => 'إعداد نظام بريد إلكتروني مؤتمت كامل على Mailchimp يشمل تسلسل الترحيب وتقسيم القوائم والحملات الدورية.',
                'budget_type' => 'fixed',
                'fixed_price' => 480,
                'hourly_price'=> null,
                'date'        => now()->addDays(19)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'اختبار جودة تطبيق ويب',
                'description' => 'اختبار شامل لتطبيق ويب يتضمن اختبار وظيفي وأداء وأمان مع إعداد تقرير مفصل عن الأخطاء المكتشفة.',
                'budget_type' => 'fixed',
                'fixed_price' => 620,
                'hourly_price'=> null,
                'date'        => now()->addDays(23)->toDateString(),
                'status'      => 'in_progress',
            ],
            [
                'title'       => 'برمجة نظام دفع إلكتروني',
                'description' => 'دمج بوابات دفع متعددة في تطبيق ويب تشمل Stripe وPayPal والبطاقات المحلية مع نظام استرداد المبالغ والتقارير.',
                'budget_type' => 'hourly',
                'fixed_price' => null,
                'hourly_price'=> 48,
                'date'        => now()->addDays(38)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'بحث ودراسة جدوى مشروع',
                'description' => 'إعداد دراسة جدوى اقتصادية لمشروع تجاري جديد مع تحليل المنافسين وحجم السوق والعوائد المتوقعة.',
                'budget_type' => 'fixed',
                'fixed_price' => 850,
                'hourly_price'=> null,
                'date'        => now()->addDays(32)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'تطوير نظام إدارة محتوى مخصص',
                'description' => 'بناء CMS مخصص لمجلة إلكترونية يدعم إدارة المقالات والفئات والكتّاب والتعليقات مع نظام موافقة.',
                'budget_type' => 'fixed',
                'fixed_price' => 3200,
                'hourly_price'=> null,
                'date'        => now()->addDays(80)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'تصميم إنفوغرافيك إحصائي',
                'description' => 'تصميم 10 إنفوغرافيك احترافية لتمثيل بيانات إحصائية بصورة جذابة لاستخدامها في التقارير ووسائل التواصل.',
                'budget_type' => 'fixed',
                'fixed_price' => 350,
                'hourly_price'=> null,
                'date'        => now()->addDays(15)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'استشارة وتدريب فريق تقني',
                'description' => 'تقديم جلسات تدريبية لفريق مطورين على Laravel وأفضل ممارسات البرمجة وإعداد خارطة طريق تقنية للمشروع.',
                'budget_type' => 'hourly',
                'fixed_price' => null,
                'hourly_price'=> 70,
                'date'        => now()->addDays(45)->toDateString(),
                'status'      => 'open',
            ],
            [
                'title'       => 'تطوير بوت تيليغرام للأعمال',
                'description' => 'تطوير بوت تيليغرام متكامل لاستقبال الطلبات وإرسال الإشعارات وإدارة العملاء مع لوحة تحكم ويب.',
                'budget_type' => 'fixed',
                'fixed_price' => 750,
                'hourly_price'=> null,
                'date'        => now()->addDays(28)->toDateString(),
                'status'      => 'in_progress',
            ],
            [
                'title'       => 'إعداد نظام backup وrestore',
                'description' => 'إعداد نظام نسخ احتياطي تلقائي لقواعد البيانات والملفات مع آلية استعادة سريعة واختبار دوري.',
                'budget_type' => 'fixed',
                'fixed_price' => 420,
                'hourly_price'=> null,
                'date'        => now()->addDays(12)->toDateString(),
                'status'      => 'closed',
            ],
            [
                'title'       => 'تطوير متجر WooCommerce متقدم',
                'description' => 'تطوير متجر WooCommerce متقدم مع إضافات مخصصة وربط مع نظام المحاسبة والمستودع وبوابات الدفع المحلية.',
                'budget_type' => 'fixed',
                'fixed_price' => 2600,
                'hourly_price'=> null,
                'date'        => now()->addDays(70)->toDateString(),
                'status'      => 'open',
            ],
        ];

        foreach ($projects as $index => $project) {
            $userId = $clientUserIds[$index % count($clientUserIds)];

            DB::table('projects')->insert([
                'user_id'      => $userId,
                'title'        => $project['title'],
                'description'  => $project['description'],
                'budget_type'  => $project['budget_type'],
                'hourly_price' => $project['hourly_price'],
                'fixed_price'  => $project['fixed_price'],
                'date'         => $project['date'],
                'status'       => $project['status'],
                'file_path'    => null,
                'created_at'   => now()->subDays(rand(1, 60)),
                'updated_at'   => now(),
            ]);
        }
    }
}
